### ISSUE TITLE
Build node.js vagrant machine

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/wycliffe-urbana-2015#10]

**Comment by stealthybox** [comment]
We approved a pull request from my repository that finishes this.
My Vagrantfile installs npm, node, git, and bower.

The Postgres package is not installing properly. (not found?)

**Comment by bbriggs** [comment]
See #17

**Comment by bbriggs** [comment]
#47 partially fixes this

**Comment by bbriggs** [comment]
Finished by #51
