### ISSUE TITLE
Build web stack

### ISSUE THREAD

**Issue by CunningJD** [bbriggs/wycliffe-urbana-2015#17]

**Comment by stealthybox** [comment]
Stack is in place under webserver/hackstack.
Vagrantfile defines vm with nodejs, npm, bower, git, and the stack in a package.
The package uses express with supporting dependencies that allow some neat features.

Static assets are in the repository under the frontend/ directory.

**Comment by bbriggs** [comment]
I have a really big PR coming for this. Major refactor. Hold off on any new development on the web stack until after that hits.

**Comment by bbriggs** [comment]
#47 partially fixes this. The rest of the fix will be to use puppet to provision node/postgres. That's coming in a future PR.

**Comment by stealthybox** [comment]
We may end up using a NoSQL database instead of Postgres, so that we can easily support sharding.

**Comment by bbriggs** [comment]
#51 finished this. If we want to use a new DB, we should address it in a future issue.
